/* manifest.js — the master index of all trainer content.
 *
 * `track` distinguishes the two parallel tracks:
 *   "core" — 4-level mock exams that mirror the real
 *                    multi-level coding assessment shape (CRUD → queries →
 *                    timestamps/TTL → capstone). 250 pts per level.
 *   "extended"     — 6-level deep-dive projects from the original trainer
 *                    build. Same archetypes stretched across more levels for
 *                    skill-building. 100 pts per level. */

export default {
  projects: [
    /* ---------- exam-faithful 4-level mock exams ---------- */
    {
      id: "mock-imdb-4",
      title: "In-Memory Database — 4-level Mock",
      domain: "Key-Value Store",
      kind: "exam",
      track: "core",
      levels: 4,
      status: "ready",
      blurb: "The canonical in-memory DB. CRUD → formatted scans → timestamps & TTL → backup/restore.",
    },
    {
      id: "mock-imdb-merge-4",
      title: "In-Memory DB (merge) — 4-level Mock",
      domain: "Key-Value Store",
      kind: "exam",
      track: "core",
      levels: 4,
      status: "ready",
      blurb: "Same L1-L3 as the canonical In-Memory DB mock — different capstone. L4 is record merge with collision rules.",
    },
    {
      id: "mock-bank-4",
      title: "Banking System — 4-level Mock",
      domain: "Banking · Transactions",
      kind: "exam",
      track: "core",
      levels: 4,
      status: "ready",
      blurb: "A banking assessment. Accounts → top_spenders → 24h cashback → account merge + historical balance.",
    },
    {
      id: "mock-bank-rollback-4",
      title: "Banking System (rollback) — 4-level Mock",
      domain: "Banking · Event Sourcing",
      kind: "exam",
      track: "core",
      levels: 4,
      status: "ready",
      blurb: "Same L1-L3 as the canonical Banking mock — different capstone. L4 is a full rollback that undoes later ops and reverses cashback.",
    },
    {
      id: "mock-cloud-4",
      title: "Cloud Storage — 4-level Mock",
      domain: "File Hosting · Quotas",
      kind: "exam",
      track: "core",
      levels: 4,
      status: "ready",
      blurb: "A cloud-storage assessment. File CRUD → prefix/suffix search → users with quotas (largest-first eviction) → compression.",
    },
    {
      id: "mock-files-4",
      title: "File Storage — 4-level Mock",
      domain: "File Storage · TTL · Rollback",
      kind: "exam",
      track: "core",
      levels: 4,
      status: "ready",
      blurb: "A file-storage assessment. file CRUD → prefix search (top 10) → TTL in seconds → rollback that recomputes TTLs.",
    },
    {
      id: "mock-dns-4",
      title: "DNS Resolver (Black Box) — 4-level Mock",
      domain: "Networking · Black-Box Resolver",
      kind: "exam",
      track: "core",
      levels: 4,
      status: "ready",
      blurb: "The hand-written DNS resolver online assessment. Iterative delegation → CNAME restart-from-root → missing glue + NXDOMAIN/NS-fallback → loop guard + cached batch. The network is a black box you may only call.",
    },

    /* ---------- 6-level extended practice (original trainer build) ---------- */
    {
      id: "integer-container",
      title: "Integer Container",
      domain: "Warm-up",
      kind: "practice",
      track: "extended",
      levels: 2,
      status: "ready",
      blurb: "The exact assessment-platform practice task — a 2-level warm-up for the testing environment.",
    },
    {
      id: "in-memory-db",
      title: "In-Memory Database (deep dive)",
      domain: "Key-Value Store",
      kind: "practice",
      track: "extended",
      levels: 6,
      status: "ready",
      blurb: "Stretched 6-level deep dive of the in-memory DB archetype. CRUD → scans → ranking → timestamps & TTL → backup/restore → search.",
    },
    {
      id: "banking-system",
      title: "Banking System (deep dive)",
      domain: "Transactions",
      kind: "practice",
      track: "extended",
      levels: 6,
      status: "ready",
      blurb: "Stretched 6-level deep dive of banking. Accounts → transfers → ranking → timestamps & holds → statements → scheduled payments.",
    },
    {
      id: "cloud-storage",
      title: "Cloud Storage Service (deep dive)",
      domain: "File Hosting",
      kind: "practice",
      track: "extended",
      levels: 6,
      status: "ready",
      blurb: "Stretched 6-level deep dive of cloud storage. File CRUD → prefix search → users & quotas → TTL → snapshots → owner search & merge.",
    },
    {
      id: "async-scheduler",
      title: "Async Job Scheduler",
      domain: "Concurrency · asyncio",
      kind: "practice",
      track: "extended",
      levels: 6,
      status: "ready",
      blurb: "Concurrency capstone — not in the canonical assessment archetypes, but invaluable async practice. Jobs → batches → priorities → timeouts → bounded concurrency → dependencies.",
    },
    {
      id: "warehouse",
      title: "Inventory & Warehouse (deep dive)",
      domain: "Inventory",
      kind: "exam",
      track: "extended",
      levels: 6,
      status: "ready",
      blurb: "Stretched 6-level deep dive of inventory. Stock CRUD → categories → ranking → perishable batches with TTL → snapshots → transfers.",
    },
    {
      id: "file-system",
      title: "In-Memory File System (deep dive)",
      domain: "File System",
      kind: "exam",
      track: "extended",
      levels: 6,
      status: "ready",
      blurb: "Stretched 6-level deep dive of a hierarchical file system. Files & directories → listing → recursive search → temp-file TTL → snapshots → move & copy.",
    },
    {
      id: "dns-resolver-full",
      title: "DNS Resolver — Full (through async Step 7)",
      domain: "Networking · Black-Box Resolver",
      kind: "exam",
      track: "extended",
      levels: 5,
      status: "ready",
      blurb: "The COMPLETE hand-written DNS resolver OA — all 7 recovered steps. The mock-dns-4 arc (iterative → CNAME restart → glue/NXDOMAIN/NS-fallback → loop guard + cached batch) plus a Level 5 async Step 7: bounded-concurrency resolve_all with an asyncio.Semaphore and in-flight de-duplication. The network is a black box you may only call.",
    },
  ],
  drills: [],
  modules: [],
};
